// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6OhXpSD8ltSGIcN1ZaafMZzuNOA_wixU',
    appId: '1:1054507585304:web:a60525a2efbbaf65b5d86d',
    messagingSenderId: '1054507585304',
    projectId: 'omega-education-centre-9a3b3',
    authDomain: 'omega-education-centre-9a3b3.firebaseapp.com',
    storageBucket: 'omega-education-centre-9a3b3.firebasestorage.app',
    measurementId: 'G-T8LTY1GR3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQmj2F3Ol66QFNoakPkg3dPf6QRijNrE',
    appId: '1:1054507585304:android:02acfda729609a3bb5d86d',
    messagingSenderId: '1054507585304',
    projectId: 'omega-education-centre-9a3b3',
    storageBucket: 'omega-education-centre-9a3b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZ77yEQjyROeBwQ-Vl6UqxN56X1tlWL4',
    appId: '1:1054507585304:ios:0549b3474cd36768b5d86d',
    messagingSenderId: '1054507585304',
    projectId: 'omega-education-centre-9a3b3',
    storageBucket: 'omega-education-centre-9a3b3.firebasestorage.app',
    iosBundleId: 'com.omegaeducation.omegaEprV2',
  );
}
